# Generated by Django 3.1.5 on 2021-12-02 11:02

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_rooms_screening_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='films',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[500, 500], upload_to=''),
        ),
    ]
