# Generated by Django 3.1.5 on 2021-12-02 11:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20211202_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[300, 300], upload_to=''),
        ),
    ]
