# Generated by Django 3.1.5 on 2021-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20211202_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
