# Generated by Django 3.1.5 on 2021-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_screening_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='start_time',
            field=models.DateField(),
        ),
    ]
