# Generated by Django 3.1.5 on 2021-12-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20211202_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='start_time',
        ),
    ]
