# Generated by Django 3.1.5 on 2021-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20211202_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='calendar',
            field=models.DateField(null=True),
        ),
    ]
