# Generated by Django 3.1.5 on 2021-12-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_auto_20211206_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='genre_id',
        ),
    ]
